default: dfx-pasement.sfd dfx-wetar.sfd dfx-snooty.sfd

dfx-pasement.sfd: dfx-pasement.cfg dfx-pasement.png
	../../sf_svn/bit7/makesfd.exe dfx-pasement.cfg $@

dfx-wetar.sfd: dfx-wetar.cfg dfx-wetar.png
	../../sf_svn/bit7/makesfd.exe dfx-wetar.cfg $@

dfx-snooty.sfd: dfx-snooty.cfg dfx-snooty.png
	../../sf_svn/bit7/makesfd.exe dfx-snooty.cfg $@

