#!/bin/sh

set -e

DOCS_SOURCE_DIR="${DFX_ROOT_SOURCE_PATH}"/docs
DOCS_INSTALL_DIR="${BUILT_PRODUCTS_DIR}/${LOCALIZED_RESOURCES_FOLDER_PATH}"
DOCS_SOURCE_FILENAME=`echo "${DFX_PLUGIN_FULL_NAME}".html | tr -d " " | tr '[:upper:]' '[:lower:]'`
DOCS_INSTALL_FILENAME="${DFX_PLUGIN_FULL_NAME} manual.html"

cp -f "${DOCS_SOURCE_DIR}/${DOCS_SOURCE_FILENAME}" "${DOCS_INSTALL_DIR}/${DOCS_INSTALL_FILENAME}"
cp -f "${DOCS_SOURCE_DIR}"/dfx-docs.css "${DOCS_INSTALL_DIR}/"
cp -f "${DOCS_SOURCE_DIR}"/COPYING.html "${DOCS_INSTALL_DIR}"/
cp -f "${DOCS_SOURCE_DIR}"/fdl.html "${DOCS_INSTALL_DIR}"/
